apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bpm-dev
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: cr.yandex/bpm-registry/bpm-gateway
    newTag: placeholder
configMapGenerator:
  - name: bpm-gateway-config
    literals:
      - LOG_LEVEL=info
