apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm-ai-service
  template:
    metadata:
      labels:
        app: bpm-ai-service
    spec:
      containers:
        - name: bpm-ai-service
          image: cr.yandex/bpm-registry/bpm-ai-service:placeholder
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
