apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-model-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm-model-repo
  template:
    metadata:
      labels:
        app: bpm-model-repo
    spec:
      containers:
        - name: bpm-model-repo
          image: cr.yandex/bpm-registry/bpm-model-repo:placeholder
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
