apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bpm
  namespace: argocd
spec:
  description: BPM-system environments
  sourceRepos:
    - https://github.com/trustmycode/bpm-gitops.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
